#!/bin/bash
# Install Kubernetes and Set Up a Local Cluster
# Starts a Kubernetes cluster on your machine
# Verifies that the cluster is running using kubectl cluster-info.
# Retrieves the available pods

# Check if minikube is installed, if not, install it
if ! command -v minikube &> dev/null/; then
  curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
  sudo install minikube-linux-amd64 /usr/local/bin/minikube && rm minikube-linux-amd64
fi

# Start a Minikube cluster using the docker driver
minikube start --driver=docker

# Interact with your cluster
minikube kubectl -- get po -A

# Verify kubectl configuration
kubectl cluster-info

# Retrieves the available pods
kubectl get pods --all-namespaces