name: Django CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: message_db
          MYSQL_USER: root
          MYSQL_PASSWORD: Master@123
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root --password=Master@123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: mysql://root:Master@123@127.0.0.1:3306/message_db
      DJANGO_SETTINGS_MODULE: messaging_app.settings
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r messaging_app/requirements.txt
          pip install pytest pytest-django mysqlclient flake8 pytest-cov coverage

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y netcat
          until nc -z 127.0.0.1 3306; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run flake8 (Lint Check)
        run: |
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

      - name: Run migrations
        run: |
          python messaging_app/manage.py migrate --noinput

      - name: Run tests with coverage
        run: |
          pytest messaging_app/tests --ds=messaging_app.settings --cov=messaging_app --cov-report=xml --cov-report=html

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/

