name: Docker Build and Push

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Git commit SHA
        id: vars
        run: echo "sha_short=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: ./messaging_app
          file: ./messaging_app/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/messaging_app:${{ env.sha_short }}
