apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  labels:
    app: messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging-app
  template:
    metadata:
      labels:
        app: messaging-app
    spec:
      containers:
        - name: messaging-app
          image: your-dockerhub-username/messaging_app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"
            - name: DB_NAME
              value: "alx_travel_app"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "your-db-password"
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
---
apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
spec:
  selector:
    app: messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
