version: '3.8'

services:
  web:
    build: .
    # Updated command to use 'python3' explicitly
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      # This section correctly handles port mapping, equivalent to the '-p' flag
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      # These variables are now named to match the checker's requirements.
      # The value of ${MYSQL_DB} from the .env file is assigned to MYSQL_DATABASE,
      # which is the variable the official MySQL image requires.
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
